name: Medium Blog Post

on:
  push:
    branches:
      - main

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm ci

    - name: Authenticate with Medium
      run: echo ${{ secrets.MEDIUM_TOKEN }} > $HOME/.medium-token
      env:
        MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}

    - name: Publish Blog
      run: npx medium-publish --path test.md --token $HOME/.medium-token

    - name: Commit Changes
      run: git add . && git commit -m "Post blog to Medium"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
