name: First Post
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read the post
        id: post
        run: echo "::set-output name=data::$(cat ./posts/post.md)"
      - uses: AIGirl10/post-medium-action@v1.6.2
        with:
          access_token: ${{ secrets.MEDIUM_ACCESS_TOKEN }}
          markdown: ${{ steps.post.outputs.data }}
          base_url: https://medium.com/@Inconspicuous10
